# Generated by Django 5.2.1 on 2025-05-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.TextField(blank=True, choices=[('low', 'low'), ('average', 'average'), ('high', 'high')], null=True),
        ),
    ]
