# Generated by Django 5.2.1 on 2025-05-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_active',
        ),
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
