services:
  backend:
    build: ./backend
    ports:
      - "8001:8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
        - "82:80"
    depends_on:
      - backend
    restart: unless-stopped
